version: '3.8'

services:
  db:
    image: postgres:18-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      -  "5432:5432"
    restart: always
    env_file:
      - configs/.env
    networks:
      - project_sem_1_network
  backend:
    image: ${DOCKER_IMAGE_NAME}
    container_name: backend
    restart: always
    env_file:
      - configs/.env
    depends_on:
      - db
    networks:
      - project_sem_1_network

volumes:
  pg_data:
networks:
  project_sem_1_network:
    driver: bridge